# Generated by Django 5.0.1 on 2024-01-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMaster',
            fields=[
                ('facultyID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('facultyPhone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('facultySubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=1)),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.facultymaster')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjectmaster')),
            ],
        ),
    ]
