# Generated by Django 5.0.1 on 2024-01-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0001_initial'),
        ('Students', '0001_initial'),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('attendenceID', models.AutoField(primary_key=True, serialize=False)),
                ('maxClasses', models.IntegerField()),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.facultymaster')),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresent', models.BooleanField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('attendanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.attendancemaster')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentmaster')),
            ],
            options={
                'unique_together': {('attendanceID', 'usn')},
            },
        ),
    ]
