# Generated by Django 5.0.1 on 2024-01-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.CharField(max_length=50, unique=True)),
                ('userPassword', models.CharField(max_length=20)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.roles')),
            ],
        ),
    ]
