# Generated by Django 5.0.1 on 2024-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('subjectCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('subjectType', models.CharField(max_length=1)),
                ('isElective', models.BooleanField()),
                ('maxIAMarks', models.IntegerField()),
                ('maxEAMarks', models.IntegerField()),
                ('IA1', models.IntegerField()),
                ('IA2', models.IntegerField()),
                ('IA3', models.IntegerField()),
                ('assignment1', models.IntegerField()),
                ('assignment2', models.IntegerField()),
                ('quiz1', models.IntegerField()),
                ('quiz2', models.IntegerField()),
                ('labRecord', models.IntegerField()),
                ('labObservation', models.IntegerField()),
                ('labViva', models.IntegerField()),
            ],
        ),
    ]
