# Generated by Django 5.0.1 on 2024-01-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaster',
            name='subjectType',
        ),
    ]
