# Generated by Django 5.0.1 on 2024-01-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_remove_subjectmaster_subjecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaster',
            name='IA1',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='IA2',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='IA3',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='assignment1',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='assignment2',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='isElective',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='labObservation',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='labRecord',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='labViva',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='maxEAMarks',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='maxIAMarks',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='quiz1',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='quiz2',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='subjectmaster',
            name='subjectName',
        ),
    ]
