# Generated by Django 5.0.1 on 2024-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0003_remove_subjectmaster_ia1_remove_subjectmaster_ia2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaster',
            name='IA1',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='IA2',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='IA3',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='assignment1',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='assignment2',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='credits',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='isElective',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='labObservation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='labRecord',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='labViva',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='maxEAMarks',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='maxIAMarks',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='quiz1',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='quiz2',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='sem',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='subjectName',
            field=models.CharField(default='COA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='subjectType',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
