# Generated by Django 5.0.1 on 2024-01-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksRecords',
            fields=[
                ('marksID', models.AutoField(primary_key=True, serialize=False)),
                ('IA1Score', models.IntegerField()),
                ('IA2Score', models.IntegerField()),
                ('IA3Score', models.IntegerField(null=True)),
                ('AverageIA', models.IntegerField()),
                ('Assignment1Score', models.IntegerField(null=True)),
                ('Assignment2Score', models.IntegerField(null=True)),
                ('Quiz1Score', models.IntegerField(null=True)),
                ('Quiz2Score', models.IntegerField(null=True)),
                ('labRecordMarks', models.IntegerField(null=True)),
                ('labObservationMarks', models.IntegerField(null=True)),
                ('labVivaMarks', models.IntegerField(null=True)),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjectmaster')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentmaster')),
            ],
        ),
    ]
