# Generated by Django 5.0.1 on 2024-01-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('dateOfBirth', models.DateField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('currentSem', models.IntegerField()),
                ('parentNumber', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('studentsubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjectmaster')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.studentmaster')),
            ],
        ),
    ]
